export enum ActionType {
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  SIGN_UP = 'SIGN_UP',
  UPDATE_AUTHENTICATION_STATE = 'UPDATE_AUTHENTICATION_STATE',
  UPDATE_LOADING_STATE = 'UPDATE_LOADING_STATE',
}
